repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        name: Ruff (lint)
        stages: [pre-commit]
        exclude: ^(notebooks/.*\.ipynb$|.*\.json$)
        args: []


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: Verificar JSONs válidos
        stages: [pre-commit]
        exclude: ^(notebooks/.*\.ipynb$|.*\.json$)

      - id: trailing-whitespace
        name: Remover espaços em branco no fim das linhas
        stages: [pre-commit]
        exclude: ^(notebooks/.*\.ipynb$|.*\.json$)

      - id: end-of-file-fixer
        name: Garantir quebra de linha no fim dos arquivos
        stages: [pre-commit]
        exclude: ^(notebooks/.*\.ipynb$|.*\.json$)
