marcas_adicionais = [
    "SHIVA",
    "BRASCOLA",
    "FERTAK",
    "NATICON",
    "NOBRE",
    "ADELBRAS",
    "STA MARINA",
    "FIRMEZA",
    "OLIPLAS",
    "STAM",
    "R.C.A",
    "CORONA",
    "TOP FIO",
    "MAKITA",
    "REXON",
    "SOPRANO",
    "FAST LUB",
    "ACQUA",
    "KIAN",
    "SOUDAL",
    "DEPLAST",
    "TATU",
    "GRENDHA",
    "PANASONIC",
    "PAULICEIA",
    "MORIA",
    "ALLTAPE",
    "PLASTILIT",
    "TITANIUM",
    "FERRARI",
    "NEGREIRA",
    "RADIAL",
    "BLUMENAU",
    "J.F METAIS",
    "ART METAIS",
    "LONAX",
    "GHEL PLUS",
    "CHEMICOLOR",
    "SANY",
    "PROAQUA",
    "BICROM",
    "WAGO",
    "TECHNA",
    "METASUL",
    "GARAPEIRA",
    "ROCO",
    "PRO FOAM",
    "DURACELL",
    "POLIBEL",
    "AGELUX",
    "REMOX",
    "RORATO",
    "WAVES",
    "LEGRAND",
    "PAPAIZ",
    "AGELUZ",
    "IMPERIAL",
    "HYDRA",
    "KITUBO",
    "NETTE",
    "SANLIMP",
    "EMA METAIS",
    "M&M" "BEARS",
    "ADTEX",
    "GALO",
    "PEGAFORTE",
    "EMAVE",
    "ELGIN",
    "LUCONI",
    "VEGA",
    "MUNDIAL",
    "DELTA",
    "COBRECOM",
    "PLASTBIG",
    "FERE",
    "SATA",
    "ALUMBRA",
    "FIOLUX",
    "PACETTA",
    "ITAMBE",
    "PEXCEL",
    "EMAVA",
    "KADESH",
    "IBERE",
    "GOLD",
    "PERLEX",
    "IMA",
    "SAFETY",
    "PIAL",
    "PLASTIK",
    "OUROLUX",
    "LED BEE",
    "BELZER",
    "PROTEG",
    "NASTRO",
    "FJ FERR",
    "SAO RAFAEL",
    "STILLUS",
    "FLASH LIMP",
    "ZUMPLAST",
    "REDY",
    "PRIMETECH",
    "SECALUX",
    "PLASTIC",
    "SUPER BONDER",
    "ARTPLAS",
    "FABER CASTELL",
    "GUARANI",
    "DEWALT",
    "ALUREM",
    "PERFIX ",
    "STELL",
    "FERROX",
    "USAF",
    "INJET",
    "CMK",
    "BEARS",
    "MINASUL",
    "DEGOMASTER",
    "SIENA",
]
marca_variacoes = {
    "TRAMONTINA": [
        "TRAMON",
        "TRAMONTINA",
        "TRAMONTINA ELE",
        "TRAMONTINA GARI",
        "TRAMONTINA MULT",
        "TRAM",
    ],
    "JOMARCA": ["JOMARCA", "JOMARC", "JOMARCA JMC", "JMC"],
    "NEW FIX": ["NEW FIX", "NEWFIX", "NEW-FIX", "NEW F"],
    "NOVA": ["NOVA TINTAS", "NOVA"],
    "DRYKO": ["DRYKO", "DRYKOPRIMER"],
    "SIKA": ["SIKATOP", "SIKA"],
    "BRASFORT": ["BRASF", "BRASFORT"],
    "ILUMI": ["ILUM", "ILUMI"],
    "DENVER": [
        "DENVER",
        "DENVERIMPER",
        "DENVERLAJE",
        "DENVERTEC",
        "DENVERCRILL",
        "DENVERFITA",
        "DENVERFIX",
    ],
    "THOMPSOM": ["THOMPSOM", "THOMP"],
    "PEGAFORTE": ["PEGAFORTE", "PEGA FORTE"],
    "CALHA FORTE": ["CALHA FORTE", "CALHA FORT"],
    "VEDACIT": ["VEDACIT", "BIANCO"],
    "LORENZETTI": ["LOREN", "LORENZETTI", "ORIG.L&C D", ".PMR D.", ".L&C ", "L&C"],
}

fornecedores_bloqueados = [
    "EDP SAO PAULO DISTRIBUICAO DE ENERGIA SA",
    "CARREFOUR COMERCIO E INDUSTRIA LTDA",
    "MAGAZINE LUIZA SA",
]

fornecedores_web_scraping = [
    "CONSTRUDIGI DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
    "CONSTRUJA DISTR. DE MATERIAIS P/ CONSTRU",
    "M.S.B. COMERCIO DE MATERIAIS PARA CONSTRUCAO",
]


fornecedores_noweb_scraping = [
    "MJLESTE DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
    "MJR CUNHA DISTRIBUIDORA DE MAT.CONSTR LTDA",
    "SOOPER HOLDING LTDA",
    "SOPREMA LTDA",
    "DENVER IMPERMEABILIZANTES, INDUSTRIA E C",
    "KADESH EQUIPAMENTOS PROFISSIONAIS LTDA",
    "Global Center Com.Ferragens Ltda",
    "MJR CUNHA DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
]

fornecedores = [
    fornecedores_bloqueados,
    fornecedores_web_scraping,
    fornecedores_noweb_scraping,
]


heavy_keywords = [
    r"\bTELHA\b",
    r"\bCUMEEIRA\b",
    r"\bPORTA\b",
    r"GABINETE",
    r"\bVASO\b",
    r"LAVAT[ÓO]RIO",
    r"\bPIA\b",
    r"\bTANQUE\b",
    r"CAIXA D'?[ÁA]GUA",
    r"CANTON",
    r"EXTENSOR",
    r"BACIA",
    r"VIAPLUS",
    r"VEDAPREN",
    r"TUBO",
    r"CONEX[ÃA]O",
    r"CANAL",
    r"LONA",
    r"TECPLUS",
    r"SIKATOP",
    r"CORRENTE",
    r"CIMENTO",
    r"ARGAMASSA",
    r"MASSA CORRIDA",
    r"MASSA ACR[IÍ]LICA",
    r"TINTA",
    r"VEDATOP",
    r"\bCALHA\b",
    r"ELETRODUTO",
    r"VAR[ÃA]O",
    r"\bPÁ\b",
    r"\bENXADA\b",
    r"CAVADEIRA",
    r"\bFORCADO\b",
    r"R[EÉ]GUA ALUM[IÍ]NIO",
    r"CARRINHO",
    r"\bESCADA\b",
    r"VARAL DE CH[ÃA]O",
    r"MANTA",
    r"DAGUA",
    r"COLUNA",
    r"\bLAV\b",
    r"TELA",
    r"CAIXA ACOP",
    r"CIMENTO",
    r"T[AÁ]BUA",
]

exclude_keywords = [
    "PARAFUSO P/ TELHA",
    "PARAF",
    "FECH",
    "SOLDA",
    "LIGACAO",
    "VALV",
    "ANEL",
    "SERRA",
    "BOCAL",
    "ABRAC",
    "CADEADO ",
    "GRELHA",
    "TORN",
    "DESEMP",
    "RALINHO",
    "PINO",
    "BOLSA",
    "ADAP",
    "PLASTICO",
    "TRAVA",
    "BOLSA",
    "LIMA",
    "RALINHO",
    "FITA",
    "CABO FLEX",
    "CABO REDE",
    "PATCH CORD",
    "COAXIAL",
    "CABO PP",
    "BATEDOR",
    "BALDE",
    "ABRAC",
    "SELATRINCA",
    "FIXADOR",
    "PILHA",
    "FRISO",
    "MOVEIS",
    "REFIL",
    "VIDRO",
    "PRATELEIRA",
    "FRANC",
    "PRESSURIZADOR",
    "FILTRO",
    "PENEIRA",
    "LUVA",
    "CALCO",
    "DISCO",
    "SUP",
    "BATEADOR",
    "MISTURADOR",
    "SAIDA",
    "CABECEIRA",
    "PNEU P/ CARRINHO",
]


SEARCH_ENGINE_ID = "532347d8c03cc4861"


mapa_abreviacoes = {
    "VM": "VERMELHO",
    "AZ": "AZUL",
    "BR": "BRANCO",
    "PT": "PRETO",
    "CZ": "CINZA",
    "UNIV": "UNIVERSAL",
    "DISJ": "DISJUNTOR",
    "UNIP": "UNIPOLAR",
    "BIP": "BIPOLAR",
    "EMBOR": "EMBORRACHADA",
    "PORC": "PORCELANA",
    "LAMP": "LAMPADA",
    "ALUM": "ALUMINIO",
    "TEMP": "TEMPERATURA",
    "DIAM": "DIAMANTADO",
    "CR": "CROMADO",
    "DESEMP": "DESEMPENADEIRA",
    "CANTON": "CANTONEIRA",
    "MARM": "MARMORE",
    "PROF": "PROFISSIONAL",
    "FURAD": "FURADEIRA",
    "B&D": "BLACK DECKER",
    "L&C": "LORENZETTI",
    "REG": "REGISTRO",
    "ESG": "ESGOTO",
    "LAMIN": "LAMINADA",
    "PLAST": "PLASTICO",
    "PARAF": "PARAFUSO",
    "CHIPB": "CHIPBOARD",
    "PHS": "PHILIPS",
    "ABRAC": "ABRACADEIRA",
    "SUP": "SUPORTE",
    "BARRAM": "BARRAMENTO",
    "GALV": "GALVANIZADO",
    "CONJ": "CONJUNTO",
    "TORN": "TORNEIRA",
    "CX": "CAIXA",
    "CX72PC": "CAIXA 72 PC",
    "INOX RED": "INOX REDONDA",
    "CLICK RED": "CLICK REDONDO",
    "SER MAR": "SERRA MARMORE",
    "SERRA MAR": "SERRA MARMORE",
    "TRANSP": "TRANSPARENTE",
    "TRIC": "TRICOTADA",
    "PIGM": "PIGMENTADA",
    "MAG": "MANGUEIRA",
    "SIST": "SISTEMA",
    "TOM": "TOMADA",
    "PROLONG": "PROLONGADOR",
    "RETANG": "RETANGULAR",
    "RESIST": "RESISTENCIA",
    "VALV": "VALVULA",
    "ESMERIL": "ESMERILHADEIRA",
    "ESMER": "ESMERILHADEIRA",
    "FURAD/PARAF": "FURADEIRA PARAFUSADEIRA",
    "CARP": "CARPINTEIRO",
    "DUP": "DUPLA",
    "JD": "JARDIM",
    "TRANC": "TRANÇADA",
    "LAV": "LAVATORIO",
    "SANIT": "SANITARIO",
    "DESC": "DESCARGA",
    "ACOPL": "ACOPLADA",
    "GD": "GRANDE",
    "FECH": "FECHADURA",
    "INT 1S": "INTERRUPTOR",
    "ACR": "ACRILICA",
    "ESM": "ESMALTE",
    "ECON": "ECONOMICO",
    "MOD": "MODULO",
    "PL": "PLACA",
    "CJ": "CONJUNTO",
    "PULVER": "PULVERIZADOR",
    "DIST": "DISTRIBUIÇÃO",
    "FERR": "FERRAMENTAS",
    "HIG": "HIGIENICA",
    "6,0X 50": "6,0X50",
    "1 SIMPLES": "1 INTERRUPTOR",
    "3INT": "3 INTERRUPTORES",
    "NEW F": "NEW FIX",
    "CANAL20X10X2M": "CANALETA 20X10X2M",
    "GAV": "GAVETA",
    "JG": "JOGO",
    "FORJ": "FORJADA",
    "PEDR": "PEDREIRO",
    "BANH": "BANHEIRO",
    "BORR": "BORRACHA",
    "ELETR": "ELETRICA",
    "MARIT": "MARITIMO",
    "BRILH": "BRILHANTE",
    "ISOL": "ISOLANTE",
    "SIF": "SIFONADO",
    "1 INT": "INTERRUPTOR",
    "EXT ILUMI": "EXTENSÃO ILUMI",
    "2TOMADAS": "2 TOMADAS",
    "COMPL": "COMPLETA",
    "COLET": "COLETORA",
    " BSP F ": "X",
    " NPT M ": "X",
    "RED EXT": "REDONDA EXTERNA",
    "1T": "1 TOMADA",
    "MEC": "MECTRONIC",
    "QUAD": "QUADRADO",
    "AM": "AMARELO",
    "BIV": "BIVOLT",
    "SOBR": "SOBREPOR",
    "SANF": "SANFONADA",
    "SANFON": "SANFONADO",
    "RETEN": "RETENÇÃO",
    "EXTEN": "EXTENSÃO",
    "TRIP": "TRIPOLAR",
    "SEXT": "SEXTAVADO",
    "SINALIZ": "SINALIZADORA",
    "PHIL": "PHILLIPS",
    "ESP": "ESPELHO",
    "ROSC": "ROSCA",
    "INST": "INSTANTÂNEA",
    "REJ": "REJUNTE",
    "DOBRAD": "DOBRADIÇA",
    "CHUV": "CHUVEIRO",
    "CHUMB": "CHUMBADOR",
    "ARGA": "ARGAMASSA",
    "REGI": "REGISTRO",
    "FRANC": "FRANCESA",
    "FECHAD": "FECHADURA",
    "CIRC": "CIRCULAR",
    "EMBORR": "EMBORRACHADA ",
    "CANAL": "CANALETA",
    "COLOR": "COLORIDA",
    "ALIC": "ALICATE",
    "MANG": "MANGUEIRA",
    "ADAP": "ADAPTADOR",
    "ACOP": "ACOPLADA",
    "BOT": "BOTINA",
    "BOTIN": "BOTINA",
    "COND": "CONDUITE",
    "CORRUG": "CORRUGADO",
    "DISC": "DISCO",
    "EMBAL": "EMBALAGEM",
    "LUMI": "LUMINARIA",
    "ALET": "ALETADA",
    "ANT": "ANTENA",
    "ESMERILH ANG": "ESMERILHADEIRA ANGULAR",
    "EL": "ELASTICA",
    "EXT NATICON": "EXTENSÃO NATICON",
    "ESPACNIVELADOR": "ESPACADOR NIVELADOR",
    "SOLD": "SOLDAVEL",
    "LIQ": "LIQUIDA",
    "PR": "PRETO",
    "HORIZ": "HORIZONTAL",
    "ACRIL": "ACRILICA",
    "ESF": "ESFERA",
    "COAX": "COAXIAL",
    "LAVAT": "LAVATORIO",
    "CONEC": "CONECTOR",
    "ALMOF": "ALMOFADADO",
    "PHILTRAM": "PHILLIPS TRAMONTINA",
    "REV": "REVOLVER",
    "ROSQJOMARCA": "ROSCADA JOMARCA",
    "PRESEXATRON": "PRESENÇA EXATRON",
    "PENZEL TERM": "PENZEL TERMINAL",
    "RESISTLC": "RESISTENCIA LORENZETTI",
    "ACAB P/ VALHIDRA ORIG4900E": "ACABAMENTO P/ VALVULA HYDRA ORIGINAL 4900E",
    "ENGRAP": "ENGATE RAPIDO",
    "ENGROSQ": "ENGATE ROSQUEADO",
    "RAPP/MANGPVC": "RAPIDO P/ MANGUEIRA PVC",
    "GR HA": "GRANDE HASTE ALUMINIO",
    "GARDEN 1/2 X3 /4": "GARDEN 1/2 X3/4",
    "ARRU": "UNIVERSAL",
    "1/4-3/8": "1/4X3/8",
    "TRANCCRISTAL": "TRANÇADA CRISTAL",
    "ALMOFADSUAVE": "ALMOFADADO SUAVE",
    "ACESS": "ACESSORIO",
    "CXDESC": "CAIXA DESCARGA",
    "MASCARA DESC": "MASCARA DESCARTAVEL",
    "MAO DESC": "MAO DESCARTAVEL",
    "FERRA": "FERRAMENTA",
    "CORR": "CORRER",
    "SEGUR": "SEGURANÇA",
    "PARAQUED": "PARAQUEDISTA",
    "ACABAM": "ACABAMENTO",
    "PIST": "PISTOLA",
    "PEQ": "PEQUENA",
    "ESPAC": "ESPACADOR",
    "NIVELAM": "NIVELAMENTO",
    "CAVAD": "CAVADEIRA",
    "TRENA F VIDRO FECH": "TRENA FIBRA VIDRO FECHADA",
    "FLUOR": "FLUORESCENTE",
    "TRANS": "TRANSPARENTE",
    "CACHIMB": "CACHIMBO",
    "ELETROD": "ELETRODUTO",
    "EXT DANEV": "EXTENSAO DANEVA",
    "SEX": "SEXTAVADO",
    "CALHAALUMINIO280G": "CALHA ALUMINIO 280G",
    "PORT ELETR F8SN": "PORTEIRO ELETRONICO",
    "INTERF": "INTERFONE",
    "TELEF": "TELEFONE",
    "PERMAN": "PERMANENTE",
    "INDL": "INDUSTRIAL",
    "AMAR": "AMARELA",
    "QUADR": "QUADRADA",
    "ROLO ESP": "ROLO ESPUMA",
    "TOMADA TEL EXT C/ 1 ADAPTADOR IMP CENTR INTERN": "TOMADA TELEFONE",
    "POLIEST": "POLIESTER",
    "ARGAM": "ARGAMASSA",
    "EXT TECHNA": "EXTENSÃO TECHNA",
    "HIDR": "HIDRAULICO",
    "TON": "TONELADAS",
    "LUBRIF": "LUBRIFICANTE",
    "BICOL": "BICOLOR",
    "POLIURET": "POLIURETANO",
    "POLI": "POLIURETANO",
    "POLIUR": "POLIURETANO",
    "TRAMONTI": "TRAMONTINA",
    "TRAM": "",
    "1TOM": "1 TOMADA",
    "1SIMP": "1 SIMPLES",
    "GORD": "GORDURA",
    "ROSQ": "ROSCADA",
    "REFLET": "REFLETOR",
    "VAL": "VALVULA",
    "FLEX": "FLEXIVEL",
    "PRES": "PRESENÇA",
    "ESGUI": "ESGUICHO",
    "ACAB": "ACABAMENTO",
    "LUMIN": "LUMINARIA",
    "LAT": "LATERAL",
    "SIMP": "SIMPLES",
    "2TOM": "2 TOMADAS",
    "VENT": "VENTILADOR ",
    "SILIC": "SILICONE",
    "SINT": "SINTETICO",
    "AMER": "AMERICANA",
    "MET": "METAL",
    "MAD": "MADEIRA",
    "PRAT": "PRATELEIRA",
    "SUPORTE EXT ZINCO": "SUPORTE EXTERNO ZINCO",
    "MAQ LAV": "MAQUINA LAVAR",
    "RAP": "RAPIDO",
    "MAQ": "MAQUINA",
    "BUCHA RED": "BUCHA REDUCAO",
    "1INT": "1 INTERRUPTOR",
    "1S": "1 INTERRUPTOR",
    "2S": "2 INTERRUPTORES",
    "ATE 25MM CONEDZ47": "25MM",
    "2INT": "2 INTERRUPTORES",
    "ENG": "ENGATE",
    "FLANG": "FLANGEADO",
    "ROS SOBERBA": "ROSCA SOBERBA",
    "MAQUINA RED": "MAQUINA REDONDA",
    "C/ FLANGEADA": "CABEÇA FLANGEADA",
    "PAN": "PANELA",
    "C/ CHA": "CHATA",
    "R MAQ": "R MAQUINA",
    "TROMB/AGULHA": "TROMBETA AGULHA",
    "CHIPBORD": "CHIPBOARD",
    "JOMARC": "JORMARCA",
    "ALMA DE AÇO": "ALMA DE AÇO ",
    "SER MARROM": "SERRA MARMORE",
    "BUCHA FIX": "BUCHA FIXACAO",
    "TIJ": "TIJOLO",
    "FUR": "FURADO",
    "FIX ALL AL": "FIX ALL ALUMINIO",
    "ZINC": "ZINCADO",
    "1EMB": "EMBALAGEM",
    "C/ CHATA": "CHATA",
    "MAR": "MARROM",
    "HIDROLET": "HIDROLETE",
    "COMP": "COMPACTA",
    "A BROCANTE": "AUTO BROCANTE",
    "R SOB (B)": "ROSCA SOBERBA",
    "0,14A4,0M": "0,14X4,0M",
    "4509 X1.1/2": "4509 X 1.1/2",
    "AJUST": "AJUSTAVEL",
    "05 A 6,0M": "05X6,0M",
    "08 A 4,0M": "08X4,0M",
    "4EM1": "",
    "INT. 1S+TOM": "INTERRUPTOR +TOMADA",
    "RL50": "ROLO 50",
    "RL 25": "ROLO 25",
    "3TOM": "3 TOMADAS",
    "4TOM": "4 TOMADAS",
    "5TOM": "5 TOMADAS",
    "LUZ PHILIPS 9/64 ": "LUZ PHILIPS 9/64X",
    "QUINT": "QUINTUPLA",
    "SIMPL": "SIMPLES",
    "C/ PL": "COM PLACA",
    "C/PL": "COM PLACA","
    "PL MILL": "PLACA MILL",
    "C/CX": "",
    "TRAMON": "",
    "GIGANT": "GIGANTE",
    "4INT": "4 INTERRUPTORES",
    "5INT": "5 INTERRUPTORES",
    "6INT": "6 INTERRUPTORES",
    "1MOD": "1 MODULO",
    "2MOD": "2 MODULOS",
    "C/ BRANCO": "BRANCO",
    "1S 1 SIMPL": "1 INTERRUPTOR",
    "2SS 2 SIMPLES": "2 INTERRUPTORES",
    "2INT.SIM+TOM2P+T10A": "2 INTERRUPTORES + TOMADA 2P + T 10A",
    "2P+T10A ": "2P+T 10A ",
    "T10A": "T 10A",
    "1P+TOM": "1 INTERRUPTOR + TOMADA",
    "RET EXT": "RETANGULAR EXTERNA",
    "2 SIMPLES": "2 INTERRUPTORES",
    "ACO10M": "ACO 10M",
    "ACO20M": "ACO 20M",
    "ACO30M": "ACO 30M",
    "ACO15M": "ACO 15M",
    "1,1/": "1 1/",
    "25MM (3/4)": "3/4",
    "3/4 (25MM)": "3/4",
    "TRAMONT": "TRAMONTINA",
    "METRO/50": "50MT",
    "PRIM": "",
    "NEU/TERR": "NEUTRO",
    "1JOMARCA": "1 JOMARCA",
    "X1,1/2": "X 1 1/2",
    "ADES": "ADESIVA",
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
}
