[tool.ruff]
line-length = 100
target-version = "py310"
fix = true
extend-select = ["I"]

select = ["E", "F", "I"]
ignore = ["E501"]

exclude = ["notebooks/*.ipynb", "*.json"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
