marcas_adicionais = [
    "SHIVA",
    "BRASCOLA",
    "FERTAK",
    "NATICON",
    "NOBRE",
    "ADELBRAS",
    "STA MARINA",
    "FIRMEZA",
    "OLIPLAS",
    "STAM",
    "R.C.A",
    "CORONA",
    "TOP FIO",
    "MAKITA",
    "REXON",
    "SOPRANO",
    "FAST LUB",
    "ACQUA",
    "KIAN",
    "SOUDAL",
    "DEPLAST",
    "TATU",
    "GRENDHA",
    "PANASONIC",
    "PAULICEIA",
    "MORIA",
    "ALLTAPE",
    "PLASTILIT",
    "TITANIUM",
    "FERRARI",
    "NEGREIRA",
    "RADIAL",
    "BLUMENAU",
    "J.F METAIS",
    "ART METAIS",
    "LONAX",
    "GHEL PLUS",
    "CHEMICOLOR",
    "SANY",
    "PROAQUA",
    "BICROM",
    "WAGO",
    "TECHNA",
    "METASUL",
    "GARAPEIRA",
    "ROCO",
    "PRO FOAM",
    "DURACELL",
    "POLIBEL",
    "AGELUX",
    "REMOX",
    "RORATO",
    "WAVES",
    "LEGRAND",
    "PAPAIZ",
    "AGELUZ",
    "IMPERIAL",
    "HYDRA",
    "KITUBO",
    "NETTE",
    "SANLIMP",
    "EMA METAIS",
    "M&M" "BEARS",
    "ADTEX",
    "GALO",
    "PEGAFORTE",
    "EMAVE",
    "ELGIN",
    "LUCONI",
    "VEGA",
    "MUNDIAL",
    "DELTA",
    "COBRECOM",
    "PLASTBIG",
    "FERE",
    "SATA",
    "ALUMBRA",
    "FIOLUX",
    "PACETTA",
    "ITAMBE",
    "PEXCEL",
    "EMAVA",
    "KADESH",
    "IBERE",
    "GOLD",
    "PERLEX",
    "IMA",
    "SAFETY",
    "PIAL",
    "PLASTIK",
    "OUROLUX",
    "LED BEE",
    "BELZER",
    "PROTEG",
    "NASTRO",
    "FJ FERR",
    "SAO RAFAEL",
    "STILLUS",
    "FLASH LIMP",
    "ZUMPLAST",
    "REDY",
    "PRIMETECH",
    "SECALUX",
    "PLASTIC",
    "SUPER BONDER",
    "ARTPLAS",
    "FABER CASTELL",
    "GUARANI",
    "DEWALT",
    "ALUREM",
    "PERFIX ",
    "STELL",
    "FERROX",
    "USAF",
    "INJET",
    "CMK",
    "BEARS",
    "MINASUL",
    "DEGOMASTER",
    "SIENA",
]

marca_variacoes = {
    "TRAMONTINA": [
        "TRAMON",
        "TRAMONTINA",
        "TRAMONTINA ELE",
        "TRAMONTINA GARI",
        "TRAMONTINA MULT",
        "TRAM",
    ],
    "JOMARCA": ["JOMARCA", "JOMARC", "JOMARCA JMC", "JMC"],
    "NEW FIX": [
        "NEW FIX",
        "NEWFIX",
        "NEW-FIX",
        "NEW F",
        "PARAF CHIPBOARD CHATA PHS",
        "PARAF SEX.ROS.SOBERBA",
    ],
    "NOVA": ["NOVA TINTAS", "NOVA"],
    "DRYKO": ["DRYKO", "DRYKOPRIMER"],
    "SIKA": ["SIKATOP", "SIKA"],
    "BRASFORT": ["BRASF", "BRASFORT"],
    "ILUMI": ["ILUM", "ILUMI"],
    "DENVER": [
        "DENVER",
        "DENVERIMPER",
        "DENVERLAJE",
        "DENVERTEC",
        "DENVERCRILL",
        "DENVERFITA",
        "DENVERFIX",
    ],
    "THOMPSOM": ["THOMPSOM", "THOMP"],
    "PEGAFORTE": ["PEGAFORTE", "PEGA FORTE"],
    "CALHA FORTE": ["CALHA FORTE", "CALHA FORT"],
    "VEDACIT": ["VEDACIT", "BIANCO"],
    "LORENZETTI": ["LOREN", "LORENZETTI", "ORIG.L&C D", ".PMR D.", ".L&C "],
    "KADESH": ["BOT FLEX ELASTICO PRETA BI"],
}



fornecedores_bloqueados = [
    "EDP SAO PAULO DISTRIBUICAO DE ENERGIA SA" "IND E COM DE TUBOS E CONEXOES FORT.COM",
    "VOTORANTIM CIMENTOS SA",
    "CABOQUINHO MATERIAIS PARA CONSTRUCAO",
    "Saint-Gobain do Brasil Produtos Ind ustriais e para Construc",
    "CARREFOUR COMERCIO E INDUSTRIA LTDA",
    "MAGAZINE LUIZA SA",
]

fornecedores_web_scraping = [
    "CONSTRUDIGI DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
    "CONSTRUJA DISTR. DE MATERIAIS P/ CONSTRU",
    "M.S.B. COMERCIO DE MATERIAIS PARA CONSTRUCAO",
]


fornecedores_noweb_scraping = [
    "MJLESTE DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
    "MJR CUNHA DISTRIBUIDORA DE MAT.CONSTR LTDA",
    "SOOPER HOLDING LTDA",
    "SOPREMA LTDA",
    "DENVER IMPERMEABILIZANTES, INDUSTRIA E C",
    "KADESH EQUIPAMENTOS PROFISSIONAIS LTDA",
    "Global Center Com.Ferragens Ltda",
    "MJR CUNHA DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
]

fornecedores = [
    fornecedores_bloqueados,
    fornecedores_web_scraping,
    fornecedores_noweb_scraping,
]
