marcas_adicionais = [
    "SHIVA",
    "BRASCOLA",
    "FERTAK",
    "NATICON",
    "NOBRE",
    "ADELBRAS",
    "STA MARINA",
    "FIRMEZA",
    "OLIPLAS",
    "STAM",
    "R.C.A",
    "CORONA",
    "TOP FIO",
    "MAKITA",
    "REXON",
    "SOPRANO",
    "FAST LUB",
    "ACQUA",
    "KIAN",
    "SOUDAL",
    "DEPLAST",
    "TATU",
    "GRENDHA",
    "PANASONIC",
    "PAULICEIA",
    "MORIA",
    "ALLTAPE",
    "PLASTILIT",
    "TITANIUM",
    "FERRARI",
    "NEGREIRA",
    "RADIAL",
    "BLUMENAU",
    "J.F METAIS",
    "ART METAIS",
    "LONAX",
    "GHEL PLUS",
    "CHEMICOLOR",
    "SANY",
    "PROAQUA",
    "BICROM",
    "WAGO",
    "TECHNA",
    "METASUL",
    "GARAPEIRA",
    "ROCO",
    "PRO FOAM",
    "DURACELL",
    "POLIBEL",
    "AGELUX",
    "REMOX",
    "RORATO",
    "WAVES",
    "LEGRAND",
    "PAPAIZ",
    "AGELUZ",
    "IMPERIAL",
    "HYDRA",
    "KITUBO",
    "NETTE",
    "SANLIMP",
    "EMA METAIS",
    "M&M" "BEARS",
    "ADTEX",
    "GALO",
    "PEGAFORTE",
    "EMAVE",
    "ELGIN",
    "LUCONI",
    "VEGA",
    "MUNDIAL",
    "DELTA",
    "COBRECOM",
    "PLASTBIG",
    "FERE",
    "SATA",
    "ALUMBRA",
    "FIOLUX",
    "PACETTA",
    "ITAMBE",
    "PEXCEL",
    "EMAVA",
    "KADESH",
    "IBERE",
    "GOLD",
    "PERLEX",
    "IMA",
    "SAFETY",
    "PIAL",
    "PLASTIK",
    "OUROLUX",
    "LED BEE",
    "BELZER",
    "PROTEG",
    "NASTRO",
    "FJ FERR",
    "SAO RAFAEL",
    "STILLUS",
    "FLASH LIMP",
    "ZUMPLAST",
    "REDY",
    "PRIMETECH",
    "SECALUX",
    "PLASTIC",
    "SUPER BONDER",
    "ARTPLAS",
    "FABER CASTELL",
    "GUARANI",
    "DEWALT",
    "ALUREM",
    "PERFIX ",
    "STELL",
    "FERROX",
    "USAF",
    "INJET",
    "CMK",
    "BEARS",
    "MINASUL",
    "DEGOMASTER",
    "SIENA",
]
marca_variacoes = {
    "TRAMONTINA": [
        "TRAMON",
        "TRAMONTINA",
        "TRAMONTINA ELE",
        "TRAMONTINA GARI",
        "TRAMONTINA MULT",
        "TRAM",
    ],
    "JOMARCA": ["JOMARCA", "JOMARC", "JOMARCA JMC", "JMC"],
    "NEW FIX": ["NEW FIX", "NEWFIX", "NEW-FIX", "NEW F"],
    "NOVA": ["NOVA TINTAS", "NOVA"],
    "DRYKO": ["DRYKO", "DRYKOPRIMER"],
    "SIKA": ["SIKATOP", "SIKA"],
    "BRASFORT": ["BRASF", "BRASFORT"],
    "ILUMI": ["ILUM", "ILUMI"],
    "DENVER": [
        "DENVER",
        "DENVERIMPER",
        "DENVERLAJE",
        "DENVERTEC",
        "DENVERCRILL",
        "DENVERFITA",
        "DENVERFIX",
    ],
    "THOMPSOM": ["THOMPSOM", "THOMP"],
    "PEGAFORTE": ["PEGAFORTE", "PEGA FORTE"],
    "CALHA FORTE": ["CALHA FORTE", "CALHA FORT"],
    "VEDACIT": ["VEDACIT", "BIANCO"],
    "LORENZETTI": ["LOREN", "LORENZETTI", "ORIG.L&C D", ".PMR D.", ".L&C ", "L&C"],
}

fornecedores_bloqueados = [
    "EDP SAO PAULO DISTRIBUICAO DE ENERGIA SA",
    "CARREFOUR COMERCIO E INDUSTRIA LTDA",
    "MAGAZINE LUIZA SA",
]

fornecedores_web_scraping = [
    "CONSTRUDIGI DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
    "CONSTRUJA DISTR. DE MATERIAIS P/ CONSTRU",
    "M.S.B. COMERCIO DE MATERIAIS PARA CONSTRUCAO",
]


fornecedores_noweb_scraping = [
    "MJLESTE DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
    "MJR CUNHA DISTRIBUIDORA DE MAT.CONSTR LTDA",
    "SOOPER HOLDING LTDA",
    "SOPREMA LTDA",
    "DENVER IMPERMEABILIZANTES, INDUSTRIA E C",
    "KADESH EQUIPAMENTOS PROFISSIONAIS LTDA",
    "Global Center Com.Ferragens Ltda",
    "MJR CUNHA DISTRIBUIDORA DE MATERIAIS PARA CONSTRUCAO LTDA",
]

fornecedores = [
    fornecedores_bloqueados,
    fornecedores_web_scraping,
    fornecedores_noweb_scraping,
]


heavy_keywords = [
    r"\bTELHA\b",
    r"\bCUMEEIRA\b",
    r"\bPORTA\b",
    r"GABINETE",
    r"\bVASO\b",
    r"LAVAT[ÓO]RIO",
    r"\bPIA\b",
    r"\bTANQUE\b",
    r"CAIXA D'?[ÁA]GUA",
    r"CANTON",
    r"EXTENSOR",
    r"BACIA",
    r"VIAPLUS",
    r"VEDAPREN",
    r"TUBO",
    r"CONEX[ÃA]O",
    r"CANAL",
    r"LONA",
    r"TECPLUS",
    r"SIKATOP",
    r"CORRENTE",
    r"CIMENTO",
    r"ARGAMASSA",
    r"MASSA CORRIDA",
    r"MASSA ACR[IÍ]LICA",
    r"TINTA",
    r"VEDATOP",
    r"\bCALHA\b",
    r"ELETRODUTO",
    r"VAR[ÃA]O",
    r"\bPÁ\b",
    r"\bENXADA\b",
    r"CAVADEIRA",
    r"\bFORCADO\b",
    r"R[EÉ]GUA ALUM[IÍ]NIO",
    r"CARRINHO",
    r"\bESCADA\b",
    r"VARAL DE CH[ÃA]O",
    r"MANTA",
    r"DAGUA",
    r"COLUNA",
    r"\bLAV\b",
    r"TELA",
    r"CAIXA ACOP",
    r"CIMENTO",
    r"T[AÁ]BUA",
]

exclude_keywords = [
    "PARAFUSO P/ TELHA",
    "PARAF",
    "FECH",
    "SOLDA",
    "LIGACAO",
    "VALV",
    "ANEL",
    "SERRA",
    "BOCAL",
    "ABRAC",
    "CADEADO ",
    "GRELHA",
    "TORN",
    "DESEMP",
    "RALINHO",
    "PINO",
    "BOLSA",
    "ADAP",
    "PLASTICO",
    "TRAVA",
    "BOLSA",
    "LIMA",
    "RALINHO",
    "FITA",
    "CABO FLEX",
    "CABO REDE",
    "PATCH CORD",
    "COAXIAL",
    "CABO PP",
    "BATEDOR",
    "BALDE",
    "ABRAC",
    "SELATRINCA",
    "FIXADOR",
    "PILHA",
    "FRISO",
    "MOVEIS",
    "REFIL",
    "VIDRO",
    "PRATELEIRA",
    "FRANC",
    "PRESSURIZADOR",
    "FILTRO",
    "PENEIRA",
    "LUVA",
    "CALCO",
    "DISCO",
    "SUP",
    "BATEADOR",
    "MISTURADOR",
    "SAIDA",
    "CABECEIRA",
    "PNEU P/ CARRINHO",
]


SEARCH_ENGINE_ID = "532347d8c03cc4861"


mapa_abreviacoes = {
    "VM": "VERMELHO",
    "AZ": "AZUL",
    "BR": "BRANCO",
    "PT": "PRETO",
    "CZ": "CINZA",
    "UNIV": "UNIVERSAL",
    "DISJ": "DISJUNTOR",
    "UNIP": "UNIPOLAR",
    "BIP": "BIPOLAR",
    "EMBOR": "EMBORRACHADA",
    "RED": "REDONDO",
    "PORC": "PORCELANA",
    "LAMP": "LAMPADA",
    "ALUM": "ALUMINIO",
    "TEMP": "TEMPERATURA",
    "DIAM": "DIAMANTADO",
    "CR": "CROMADO",
    "DESEMP": "DESEMPENADEIRA",
    "CANTON": "CANTONEIRA",
    "MARM": "MARMORE",
    "PROF": "PROFISSIONAL",
    "FURAD": "FURADEIRA",
    "B&D": "BLACK DECKER",
    "L&C": "LORENZETTI",
    "REG": "REGISTRO",
    "ESG": "ESGOTO",
    "LAMIN": "LAMINADA",
    "PLAST": "PLASTICO",
    "PARAF": "PARAFUSO",
    "CHIPB": "CHIPBOARD",
    "PHS": "PHILIPS",
    "ABRAC": "ABRACADEIRA",
    "SUP": "SUPORTE",
    "BARRAM": "BARRAMENTO",
    "GALV": "GALVANIZADO",
    "CONJ": "CONJUNTO",
    "TORN": "TORNEIRA",
    "CX": "CAIXA",
    "MAR": "MARROM",
    "TRANSP": "TRANSPARENTE",
    "TRIC": "TRICOTADA",
    "PIGM": "PIGMENTADA",
    "MAG": "MANGUEIRA",
    "SIST": "SISTEMA",
    "TOM": "TOMADA",
    "PROLONG": "PROLONGADOR",
    "RETANG": "RETANGULAR",
    "RESIST": "RESISTENCIA",
    "VALV": "VALVULA",
    "ESMERIL": "ESMERILHADEIRA",
    "DUP": "DUPLA",
    "JD": "JARDIM",
    "TRANC": "TRANÇADA",
    "LAV": "LAVATORIO",
    "SANIT": "SANITARIO",
    "DESC": "DESCARGA",
    "ACOPL": "ACOPLADA",
    "GD": "GRANDE",
    "FECH": "FECHADURA",
    "ACR": "ACRILICA",
    "INT": "INTERNA",
    "ESM": "ESMALTE",
    "ECON": "ECONOMICO",
    "MOD": "MODULO",
    "PL": "PLACA",
    "CJ": "CONJUNTO",
    "PULVER": "PULVERIZADOR",
    "DIST": "DISTRIBUIÇÃO",
    "FERR": "FERRAMENTAS",
    "GAV": "GAVETAS",
    "JG": "JOGO",
    "FORJ": "FORJADA",
    "PEDR": "PEDREIRO",
    "BANH": "BANHEIRO",
    "BORR": "BORRACHA",
    "ELETR": "ELETRICA",
    "MARIT": "MARITIMO",
    "BRILH": "BRILHANTE",
    "TERM": "TERMINAL",
    "ISOL": "ISOLANTE",
    "SIF": "SIFONADO",
    "MEC": "MECTRONIC",
    "QUAD": "QUADRADO",
    "AM": "AMARELO",
    "BIV": "BIVOLT",
    "SOBR": "SOBREPOR",
    "SANF": "SANFONADA",
    "RETEN": "RETENÇÃO",
    "EXTEN": "EXTENSÃO",
    "TRIP": "TRIPOLAR",
    "SEXT": "SEXTAVADO",
    "SINALIZ": "SINALIZADORA",
    "PHIL": "PHILLIPS",
    "ESP": "ESPELHO",
    "ROSC": "ROSCADA",
    "INST": "INSTANTÂNEA",
    "REJ": "REJUNTE",
    "DOBRAD": "DOBRADIÇA",
    "CHUV": "CHUVEIRO",
    "CHUMB": "CHUMBADOR",
    "ARGA": "ARGAMASSA",
    "REGI": "REGISTRO",
    "FRANC": "FRANCESA",
    "FECHAD": "FECHADURA",
    "CIRC": "CIRCULAR",
    "EMBORR": "EMBORRACHADA ",
    "CANAL": "CANALETA",
    "COLOR": "COLORIDA",
}
